### ISSUE TITLE
TypeError: this.adapter.addAll is not a function

### ISSUE THREAD

**Issue by centrual** [elegantmonkeys/socket.io-pubsub#4]
Hello @elegantmonkeys

Socket io updated the version and added addAll method for join multiple rooms.
Also google cloud version bumped to 0.48.0 too.

Current version of socket.io-pubsub not peer with google-cloud version 0.48.0 and not working with latest version of socket.io server.

Have a great day!

**Comment by idoshamun** [comment]
Hi @centrual ,
Would it be possible for you to submit a PR?

Thanks for your contribution!

**Comment by centrual** [comment]
Information is not correct, let i fix:
1) Github version of socket.io not working with socket.io-pubsub
2) google-cloud updated to 0.48.0, socket.io-pubsub working with 0.47.0

I'll check it soon, currently it is working with socket.io 1.7.3 and google-cloud 0.47.0

**Comment by centrual** [comment]
google-cloud version fix: https://github.com/elegantmonkeys/socket.io-pubsub/pull/5

I'll wait for new version release from socket.io for update.
